name: io production workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: deploying io in production
        uses: actions/checkout@v3
      - run: make build-production
      - run: make start-production
